from __future__ import annotations

from typing import Any, Dict, List


ExerciseDict = Dict[str, Any]


def make_examples(*pairs: tuple[str, str]) -> List[Dict[str, str]]:
    return [{"input": input_value, "output": output_value} for input_value, output_value in pairs]


EXERCISES: List[ExerciseDict] = [
    {
        "id": "level-1-step-1",
        "level": 1,
        "step": 1,
        "title": "Le coffre des coquillages",
        "zone": "La Plage des Variables",
        "story": "Un petit coffre s'est ouvert sur la plage. Pour ranger les coquillages, tu dois additionner deux nombres magiques.",
        "instructions": "Ecris une fonction qui reçoit deux nombres et renvoie leur somme.",
        "short_objective": "Additionner deux nombres.",
        "function_name": "addition_coquillages",
        "starter_code": "def addition_coquillages(a, b):\n    # Retourne la somme de a et b\n    return 0\n",
        "examples": make_examples(("addition_coquillages(2, 3)", "5"), ("addition_coquillages(10, 1)", "11")),
        "tests": [
            {"name": "2 + 3", "assertion": "assert addition_coquillages(2, 3) == 5, '2 + 3 doit faire 5'"},
            {"name": "0 + 7", "assertion": "assert addition_coquillages(0, 7) == 7, '0 + 7 doit faire 7'"},
            {"name": "-1 + 1", "assertion": "assert addition_coquillages(-1, 1) == 0, '-1 + 1 doit faire 0'"},
            {"name": "8 + 12", "assertion": "assert addition_coquillages(8, 12) == 20, '8 + 12 doit faire 20'"},
            {"name": "50 + 5", "assertion": "assert addition_coquillages(50, 5) == 55, '50 + 5 doit faire 55'"},
        ],
        "success_message": "Bravo, le coffre s'ouvre et les coquillages brillent.",
        "failure_hint": "Relis bien la consigne : ta fonction doit renvoyer la somme des deux nombres.",
    },
    {
        "id": "level-1-step-2",
        "level": 1,
        "step": 2,
        "title": "Le perroquet qui salue",
        "zone": "La Plage des Variables",
        "story": "Un perroquet curieux veut apprendre à dire bonjour à chaque visiteur.",
        "instructions": "Ecris une fonction qui reçoit un prénom et renvoie la phrase Bonjour suivie du prénom.",
        "short_objective": "Assembler une phrase avec une chaîne.",
        "function_name": "bonjour_pythonaute",
        "starter_code": "def bonjour_pythonaute(prenom):\n    # Retourne une phrase de salutation\n    return ''\n",
        "examples": make_examples(("bonjour_pythonaute('Lina')", "'Bonjour Lina'"), ("bonjour_pythonaute('Noe')", "'Bonjour Noe'")),
        "tests": [
            {"name": "Bonjour Lina", "assertion": "assert bonjour_pythonaute('Lina') == 'Bonjour Lina', 'Il faut ajouter Bonjour avant le prénom'"},
            {"name": "Bonjour Tom", "assertion": "assert bonjour_pythonaute('Tom') == 'Bonjour Tom', 'Tom doit être salué correctement'"},
            {"name": "Bonjour Zoe", "assertion": "assert bonjour_pythonaute('Zoe') == 'Bonjour Zoe', 'Zoe doit être saluée correctement'"},
            {"name": "Bonjour Ada", "assertion": "assert bonjour_pythonaute('Ada') == 'Bonjour Ada', 'Ada doit être saluée correctement'"},
            {"name": "Bonjour Max", "assertion": "assert bonjour_pythonaute('Max') == 'Bonjour Max', 'Max doit être salué correctement'"},
        ],
        "success_message": "Le perroquet crie bonjour à toute l'ile.",
        "failure_hint": "Pense à renvoyer une seule chaîne qui commence par Bonjour puis un espace.",
    },
    {
        "id": "level-2-step-1",
        "level": 2,
        "step": 3,
        "title": "Le pont du soleil",
        "zone": "La Foret des Conditions",
        "story": "Pour traverser un petit pont doré, tu dois dire si le nombre reçu est positif ou non.",
        "instructions": "Ecris une fonction qui renvoie 'positif' si le nombre est plus grand que 0, sinon 'pas positif'.",
        "short_objective": "Utiliser if / else.",
        "function_name": "message_soleil",
        "starter_code": "def message_soleil(nombre):\n    # Utilise if / else\n    return ''\n",
        "examples": make_examples(("message_soleil(4)", "'positif'"), ("message_soleil(0)", "'pas positif'")),
        "tests": [
            {"name": "4 est positif", "assertion": "assert message_soleil(4) == 'positif', '4 doit renvoyer positif'"},
            {"name": "1 est positif", "assertion": "assert message_soleil(1) == 'positif', '1 doit renvoyer positif'"},
            {"name": "0 n'est pas positif", "assertion": "assert message_soleil(0) == 'pas positif', '0 doit renvoyer pas positif'"},
            {"name": "-3 n'est pas positif", "assertion": "assert message_soleil(-3) == 'pas positif', '-3 doit renvoyer pas positif'"},
            {"name": "-1 n'est pas positif", "assertion": "assert message_soleil(-1) == 'pas positif', '-1 doit renvoyer pas positif'"},
        ],
        "success_message": "Le pont s'illumine et tu peux avancer.",
        "failure_hint": "Teste le cas où le nombre est plus grand que 0, puis le reste dans le else.",
    },
    {
        "id": "level-2-step-2",
        "level": 2,
        "step": 4,
        "title": "Le hibou des nombres pairs",
        "zone": "La Foret des Conditions",
        "story": "Un hibou veille sur la foret. Il aime seulement les nombres pairs.",
        "instructions": "Ecris une fonction qui renvoie 'pair' si le nombre est pair, sinon 'impair'.",
        "short_objective": "Reconnaître un nombre pair.",
        "function_name": "pair_ou_impair",
        "starter_code": "def pair_ou_impair(nombre):\n    # Utilise le reste de la division par 2\n    return ''\n",
        "examples": make_examples(("pair_ou_impair(8)", "'pair'"), ("pair_ou_impair(5)", "'impair'")),
        "tests": [
            {"name": "8 est pair", "assertion": "assert pair_ou_impair(8) == 'pair', '8 est pair'"},
            {"name": "5 est impair", "assertion": "assert pair_ou_impair(5) == 'impair', '5 est impair'"},
            {"name": "0 est pair", "assertion": "assert pair_ou_impair(0) == 'pair', '0 est pair'"},
            {"name": "11 est impair", "assertion": "assert pair_ou_impair(11) == 'impair', '11 est impair'"},
            {"name": "14 est pair", "assertion": "assert pair_ou_impair(14) == 'pair', '14 est pair'"},
        ],
        "success_message": "Le hibou hoche la tete et t'autorise a passer.",
        "failure_hint": "Un nombre pair laisse un reste de 0 quand on le divise par 2.",
    },
    {
        "id": "level-3-step-1",
        "level": 3,
        "step": 5,
        "title": "La clochette magique",
        "zone": "Le Village des Fonctions",
        "story": "Au village, une clochette double la force des objets qu'on lui confie.",
        "instructions": "Ecris une fonction qui reçoit un nombre et renvoie le double de ce nombre.",
        "short_objective": "Créer une fonction très simple.",
        "function_name": "double_magique",
        "starter_code": "def double_magique(nombre):\n    # Retourne le double\n    return 0\n",
        "examples": make_examples(("double_magique(4)", "8"), ("double_magique(9)", "18")),
        "tests": [
            {"name": "Double de 4", "assertion": "assert double_magique(4) == 8, 'Le double de 4 est 8'"},
            {"name": "Double de 1", "assertion": "assert double_magique(1) == 2, 'Le double de 1 est 2'"},
            {"name": "Double de 0", "assertion": "assert double_magique(0) == 0, 'Le double de 0 est 0'"},
            {"name": "Double de 7", "assertion": "assert double_magique(7) == 14, 'Le double de 7 est 14'"},
            {"name": "Double de 12", "assertion": "assert double_magique(12) == 24, 'Le double de 12 est 24'"},
        ],
        "success_message": "La clochette tinte et la magie repond.",
        "failure_hint": "Ton résultat doit être le nombre multiplié par 2.",
    },
    {
        "id": "level-3-step-2",
        "level": 3,
        "step": 6,
        "title": "Le miroir du village",
        "zone": "Le Village des Fonctions",
        "story": "Un miroir ancien répète les mots deux fois pour vérifier qu'ils sont bien lancés.",
        "instructions": "Ecris une fonction qui reçoit un mot et renvoie ce mot répété 2 fois.",
        "short_objective": "Renvoyer une nouvelle chaîne.",
        "function_name": "repete_mot",
        "starter_code": "def repete_mot(mot):\n    # Retourne le mot deux fois\n    return ''\n",
        "examples": make_examples(("repete_mot('py')", "'pypy'"), ("repete_mot('go')", "'gogo'")),
        "tests": [
            {"name": "py -> pypy", "assertion": "assert repete_mot('py') == 'pypy', 'Le mot doit être répété 2 fois'"},
            {"name": "go -> gogo", "assertion": "assert repete_mot('go') == 'gogo', 'Le mot doit être répété 2 fois'"},
            {"name": "a -> aa", "assertion": "assert repete_mot('a') == 'aa', 'Le mot doit être répété 2 fois'"},
            {"name": "chat -> chatchat", "assertion": "assert repete_mot('chat') == 'chatchat', 'Le mot doit être répété 2 fois'"},
            {"name": "x -> xx", "assertion": "assert repete_mot('x') == 'xx', 'Le mot doit être répété 2 fois'"},
        ],
        "success_message": "Le miroir scintille et confirme ton sort.",
        "failure_hint": "Tu peux multiplier une chaîne par 2 pour la répéter.",
    },
    {
        "id": "level-4-step-1",
        "level": 4,
        "step": 7,
        "title": "Le sac de pierres bleues",
        "zone": "Le Pont des Listes",
        "story": "Sur le pont, tu trouves un sac de pierres bleues. Il faut compter combien il y en a.",
        "instructions": "Ecris une fonction qui reçoit une liste et renvoie le nombre d'éléments dans cette liste.",
        "short_objective": "Compter les éléments d'une liste.",
        "function_name": "compte_pierres",
        "starter_code": "def compte_pierres(pierres):\n    # Retourne la taille de la liste\n    return 0\n",
        "examples": make_examples(("compte_pierres([1, 2, 3])", "3"), ("compte_pierres([])", "0")),
        "tests": [
            {"name": "Liste de 3 éléments", "assertion": "assert compte_pierres([1, 2, 3]) == 3, 'La liste contient 3 éléments'"},
            {"name": "Liste vide", "assertion": "assert compte_pierres([]) == 0, 'Une liste vide contient 0 élément'"},
            {"name": "Liste de 1 élément", "assertion": "assert compte_pierres(['a']) == 1, 'La liste contient 1 élément'"},
            {"name": "Liste de 5 éléments", "assertion": "assert compte_pierres([9, 8, 7, 6, 5]) == 5, 'La liste contient 5 éléments'"},
            {"name": "Liste mixte", "assertion": "assert compte_pierres([1, 'b', True]) == 3, 'La liste contient 3 éléments'"},
        ],
        "success_message": "Le sac s'ouvre et libère des étincelles bleues.",
        "failure_hint": "La fonction `len(...)` peut t'aider à compter les éléments d'une liste.",
    },
    {
        "id": "level-4-step-2",
        "level": 4,
        "step": 8,
        "title": "La premiere planche",
        "zone": "Le Pont des Listes",
        "story": "Une planche magique demande le premier objet de la liste pour laisser passer les explorateurs.",
        "instructions": "Ecris une fonction qui reçoit une liste non vide et renvoie son premier élément.",
        "short_objective": "Lire le premier élément d'une liste.",
        "function_name": "premiere_planche",
        "starter_code": "def premiere_planche(objets):\n    # La liste n'est jamais vide\n    return None\n",
        "examples": make_examples(("premiere_planche([5, 6, 7])", "5"), ("premiere_planche(['soleil', 'lune'])", "'soleil'")),
        "tests": [
            {"name": "Premier nombre", "assertion": "assert premiere_planche([5, 6, 7]) == 5, 'Le premier élément est 5'"},
            {"name": "Premier mot", "assertion": "assert premiere_planche(['soleil', 'lune']) == 'soleil', 'Le premier élément est soleil'"},
            {"name": "Premier booléen", "assertion": "assert premiere_planche([True, False]) is True, 'Le premier élément est True'"},
            {"name": "Liste d'un seul élément", "assertion": "assert premiere_planche([42]) == 42, 'Le premier élément est 42'"},
            {"name": "Premier animal", "assertion": "assert premiere_planche(['chat', 'chien', 'panda']) == 'chat', 'Le premier élément est chat'"},
        ],
        "success_message": "La planche se pose bien droite sous tes pieds.",
        "failure_hint": "Dans une liste, le premier élément est à la position 0.",
    },
    {
        "id": "level-5-step-1",
        "level": 5,
        "step": 9,
        "title": "Les lucioles du rivage",
        "zone": "La Riviere des Boucles For",
        "story": "Des lucioles se posent une à une sur la rivière. Tu dois compter leur lumière totale.",
        "instructions": "Ecris une fonction qui reçoit une liste de nombres et renvoie leur somme en utilisant une boucle for.",
        "short_objective": "Additionner des éléments avec une boucle for.",
        "function_name": "somme_lucioles",
        "starter_code": "def somme_lucioles(nombres):\n    total = 0\n    # Parcours la liste avec une boucle for\n    return total\n",
        "examples": make_examples(("somme_lucioles([1, 2, 3])", "6"), ("somme_lucioles([5])", "5")),
        "tests": [
            {"name": "1 + 2 + 3", "assertion": "assert somme_lucioles([1, 2, 3]) == 6, 'La somme doit être 6'"},
            {"name": "Liste vide", "assertion": "assert somme_lucioles([]) == 0, 'La somme d\\'une liste vide vaut 0'"},
            {"name": "Liste simple", "assertion": "assert somme_lucioles([5]) == 5, 'La somme doit être 5'"},
            {"name": "4 + 4 + 4", "assertion": "assert somme_lucioles([4, 4, 4]) == 12, 'La somme doit être 12'"},
            {"name": "10 + 0 + 1", "assertion": "assert somme_lucioles([10, 0, 1]) == 11, 'La somme doit être 11'"},
        ],
        "success_message": "Les lucioles dessinent un chemin brillant sur l'eau.",
        "failure_hint": "Commence par `total = 0`, puis ajoute chaque nombre dans la boucle.",
    },
    {
        "id": "level-5-step-2",
        "level": 5,
        "step": 10,
        "title": "Le collier des lettres",
        "zone": "La Riviere des Boucles For",
        "story": "Une fée fabrique un collier en accrochant toutes les lettres les unes après les autres.",
        "instructions": "Ecris une fonction qui reçoit une liste de lettres et renvoie une chaîne avec toutes les lettres collées.",
        "short_objective": "Assembler une chaîne avec une boucle for.",
        "function_name": "collier_lettres",
        "starter_code": "def collier_lettres(lettres):\n    resultat = ''\n    # Ajoute chaque lettre dans resultat\n    return resultat\n",
        "examples": make_examples(("collier_lettres(['p', 'y'])", "'py'"), ("collier_lettres(['b', 'o', 'n'])", "'bon'")),
        "tests": [
            {"name": "py", "assertion": "assert collier_lettres(['p', 'y']) == 'py', 'Le collier doit former py'"},
            {"name": "bon", "assertion": "assert collier_lettres(['b', 'o', 'n']) == 'bon', 'Le collier doit former bon'"},
            {"name": "vide", "assertion": "assert collier_lettres([]) == '', 'Une liste vide donne une chaîne vide'"},
            {"name": "abc", "assertion": "assert collier_lettres(['a', 'b', 'c']) == 'abc', 'Le collier doit former abc'"},
            {"name": "z", "assertion": "assert collier_lettres(['z']) == 'z', 'Le collier doit former z'"},
        ],
        "success_message": "Le collier s'anime et chante doucement.",
        "failure_hint": "Dans la boucle, ajoute chaque lettre à la fin de la chaîne résultat.",
    },
    {
        "id": "level-6-step-1",
        "level": 6,
        "step": 11,
        "title": "L'escalier de la grotte",
        "zone": "La Grotte des Boucles While",
        "story": "Pour descendre dans la grotte, il faut compter les marches une par une jusqu'au nombre demandé.",
        "instructions": "Ecris une fonction qui reçoit un nombre et renvoie la somme de tous les nombres de 1 jusqu'à ce nombre avec une boucle while.",
        "short_objective": "Utiliser while pour additionner.",
        "function_name": "somme_marches",
        "starter_code": "def somme_marches(nombre):\n    total = 0\n    courant = 1\n    # Utilise une boucle while\n    return total\n",
        "examples": make_examples(("somme_marches(3)", "6"), ("somme_marches(1)", "1")),
        "tests": [
            {"name": "Somme jusqu'à 3", "assertion": "assert somme_marches(3) == 6, '1 + 2 + 3 = 6'"},
            {"name": "Somme jusqu'à 1", "assertion": "assert somme_marches(1) == 1, '1 = 1'"},
            {"name": "Somme jusqu'à 4", "assertion": "assert somme_marches(4) == 10, '1 + 2 + 3 + 4 = 10'"},
            {"name": "Somme jusqu'à 5", "assertion": "assert somme_marches(5) == 15, '1 à 5 donne 15'"},
            {"name": "Somme jusqu'à 2", "assertion": "assert somme_marches(2) == 3, '1 + 2 = 3'"},
        ],
        "success_message": "Chaque marche s'allume sous tes pas.",
        "failure_hint": "Fais avancer une variable `courant` tant qu'elle est plus petite ou égale au nombre.",
    },
    {
        "id": "level-6-step-2",
        "level": 6,
        "step": 12,
        "title": "Les cristaux qui grandissent",
        "zone": "La Grotte des Boucles While",
        "story": "Des cristaux doublent de taille à chaque battement. Tu dois compter combien de doublages il faut pour atteindre une cible.",
        "instructions": "Ecris une fonction qui part de 1 et double sa valeur jusqu'à atteindre ou dépasser la cible. Renvoie le nombre de doublages.",
        "short_objective": "Boucle while avec compteur.",
        "function_name": "compte_doublages",
        "starter_code": "def compte_doublages(cible):\n    valeur = 1\n    tours = 0\n    # Double valeur jusqu'à atteindre la cible\n    return tours\n",
        "examples": make_examples(("compte_doublages(2)", "1"), ("compte_doublages(8)", "3")),
        "tests": [
            {"name": "Cible 2", "assertion": "assert compte_doublages(2) == 1, '1 devient 2 en 1 doublage'"},
            {"name": "Cible 3", "assertion": "assert compte_doublages(3) == 2, '1 -> 2 -> 4'"},
            {"name": "Cible 8", "assertion": "assert compte_doublages(8) == 3, '1 -> 2 -> 4 -> 8'"},
            {"name": "Cible 1", "assertion": "assert compte_doublages(1) == 0, 'Pas besoin de doubler pour atteindre 1'"},
            {"name": "Cible 16", "assertion": "assert compte_doublages(16) == 4, '1 -> 2 -> 4 -> 8 -> 16'"},
        ],
        "success_message": "Les cristaux pulsent au bon rythme.",
        "failure_hint": "Tant que la valeur est plus petite que la cible, double-la et ajoute 1 au compteur.",
    },
    {
        "id": "level-7-step-1",
        "level": 7,
        "step": 13,
        "title": "Les étals du marché",
        "zone": "Le Marche des Dictionnaires",
        "story": "Au marché, chaque étal a un nom et un prix. Tu dois retrouver le prix d'un fruit.",
        "instructions": "Ecris une fonction qui reçoit un dictionnaire de prix et un nom de fruit, puis renvoie le prix associé.",
        "short_objective": "Lire une valeur dans un dictionnaire.",
        "function_name": "prix_du_fruit",
        "starter_code": "def prix_du_fruit(prix, fruit):\n    # Renvoie le prix du fruit demandé\n    return 0\n",
        "examples": make_examples(("prix_du_fruit({'pomme': 2, 'poire': 3}, 'poire')", "3"), ("prix_du_fruit({'kiwi': 5}, 'kiwi')", "5")),
        "tests": [
            {"name": "Poire", "assertion": "assert prix_du_fruit({'pomme': 2, 'poire': 3}, 'poire') == 3, 'Le prix de la poire est 3'"},
            {"name": "Kiwi", "assertion": "assert prix_du_fruit({'kiwi': 5}, 'kiwi') == 5, 'Le prix du kiwi est 5'"},
            {"name": "Mangue", "assertion": "assert prix_du_fruit({'mangue': 4, 'banane': 1}, 'mangue') == 4, 'Le prix de la mangue est 4'"},
            {"name": "Pomme", "assertion": "assert prix_du_fruit({'pomme': 7, 'orange': 2}, 'pomme') == 7, 'Le prix de la pomme est 7'"},
            {"name": "Fraise", "assertion": "assert prix_du_fruit({'fraise': 6}, 'fraise') == 6, 'Le prix de la fraise est 6'"},
        ],
        "success_message": "Le marchand te remercie avec un sourire.",
        "failure_hint": "Dans un dictionnaire, on lit une valeur avec le nom de la clé entre crochets.",
    },
    {
        "id": "level-7-step-2",
        "level": 7,
        "step": 14,
        "title": "Le registre des amis",
        "zone": "Le Marche des Dictionnaires",
        "story": "Le registre du marché garde les âges des amis. Tu dois vérifier si un prénom est bien inscrit.",
        "instructions": "Ecris une fonction qui reçoit un dictionnaire et un prénom. Renvoie True si le prénom est une clé du dictionnaire, sinon False.",
        "short_objective": "Tester la présence d'une clé.",
        "function_name": "ami_present",
        "starter_code": "def ami_present(registre, prenom):\n    # Renvoie True ou False\n    return False\n",
        "examples": make_examples(("ami_present({'Lina': 10, 'Tom': 11}, 'Tom')", "True"), ("ami_present({'Lina': 10}, 'Noe')", "False")),
        "tests": [
            {"name": "Tom présent", "assertion": "assert ami_present({'Lina': 10, 'Tom': 11}, 'Tom') is True, 'Tom est bien une clé'"},
            {"name": "Noe absent", "assertion": "assert ami_present({'Lina': 10}, 'Noe') is False, 'Noe n\\'est pas une clé'"},
            {"name": "Ada présente", "assertion": "assert ami_present({'Ada': 12, 'Max': 11}, 'Ada') is True, 'Ada est bien une clé'"},
            {"name": "Zoe absente", "assertion": "assert ami_present({}, 'Zoe') is False, 'Un dictionnaire vide ne contient personne'"},
            {"name": "Mila présente", "assertion": "assert ami_present({'Mila': 9}, 'Mila') is True, 'Mila est bien une clé'"},
        ],
        "success_message": "Le registre s'ouvre et une page dorée apparaît.",
        "failure_hint": "Tu peux utiliser `in` pour savoir si une clé existe dans un dictionnaire.",
    },
    {
        "id": "level-8-step-1",
        "level": 8,
        "step": 15,
        "title": "La pierre des jumeaux",
        "zone": "Le Temple des Collections",
        "story": "Dans le temple, une pierre sacrée garde toujours une paire de nombres.",
        "instructions": "Ecris une fonction qui reçoit un tuple de deux nombres et renvoie leur somme.",
        "short_objective": "Lire un tuple simple.",
        "function_name": "somme_du_tuple",
        "starter_code": "def somme_du_tuple(paire):\n    # paire contient exactement 2 nombres\n    return 0\n",
        "examples": make_examples(("somme_du_tuple((2, 5))", "7"), ("somme_du_tuple((10, 1))", "11")),
        "tests": [
            {"name": "(2, 5)", "assertion": "assert somme_du_tuple((2, 5)) == 7, '2 + 5 = 7'"},
            {"name": "(10, 1)", "assertion": "assert somme_du_tuple((10, 1)) == 11, '10 + 1 = 11'"},
            {"name": "(0, 0)", "assertion": "assert somme_du_tuple((0, 0)) == 0, '0 + 0 = 0'"},
            {"name": "(7, 3)", "assertion": "assert somme_du_tuple((7, 3)) == 10, '7 + 3 = 10'"},
            {"name": "(4, 9)", "assertion": "assert somme_du_tuple((4, 9)) == 13, '4 + 9 = 13'"},
        ],
        "success_message": "La pierre résonne et révèle un passage secret.",
        "failure_hint": "Un tuple se lit comme une liste : premier élément à l'index 0, deuxième à l'index 1.",
    },
    {
        "id": "level-8-step-2",
        "level": 8,
        "step": 16,
        "title": "Le bassin des perles uniques",
        "zone": "Le Temple des Collections",
        "story": "Un bassin magique ne garde qu'un exemplaire de chaque perle. Tu dois compter les perles différentes.",
        "instructions": "Ecris une fonction qui reçoit une liste et renvoie combien de valeurs différentes elle contient.",
        "short_objective": "Utiliser un ensemble simple.",
        "function_name": "compte_perles_uniques",
        "starter_code": "def compte_perles_uniques(perles):\n    # Utilise un set pour garder les valeurs différentes\n    return 0\n",
        "examples": make_examples(("compte_perles_uniques([1, 1, 2, 3])", "3"), ("compte_perles_uniques(['a', 'a'])", "1")),
        "tests": [
            {"name": "1 1 2 3", "assertion": "assert compte_perles_uniques([1, 1, 2, 3]) == 3, 'Il y a 3 valeurs différentes'"},
            {"name": "a a", "assertion": "assert compte_perles_uniques(['a', 'a']) == 1, 'Il y a 1 valeur différente'"},
            {"name": "vide", "assertion": "assert compte_perles_uniques([]) == 0, 'Une liste vide contient 0 valeur différente'"},
            {"name": "5 6 5 6 7", "assertion": "assert compte_perles_uniques([5, 6, 5, 6, 7]) == 3, 'Il y a 3 valeurs différentes'"},
            {"name": "x y z", "assertion": "assert compte_perles_uniques(['x', 'y', 'z']) == 3, 'Il y a 3 valeurs différentes'"},
        ],
        "success_message": "Les perles uniques forment une constellation brillante.",
        "failure_hint": "Un `set(...)` garde une seule fois chaque valeur.",
    },
    {
        "id": "level-9-step-1",
        "level": 9,
        "step": 17,
        "title": "La tour des majuscules",
        "zone": "La Tour des Chaines",
        "story": "Dans la tour, les messages importants sont écrits en grandes lettres.",
        "instructions": "Ecris une fonction qui reçoit un mot et le renvoie en majuscules.",
        "short_objective": "Transformer une chaîne.",
        "function_name": "crie_message",
        "starter_code": "def crie_message(message):\n    # Retourne le message en majuscules\n    return ''\n",
        "examples": make_examples(("crie_message('python')", "'PYTHON'"), ("crie_message('Bonjour')", "'BONJOUR'")),
        "tests": [
            {"name": "python", "assertion": "assert crie_message('python') == 'PYTHON', 'Le mot doit être en majuscules'"},
            {"name": "Bonjour", "assertion": "assert crie_message('Bonjour') == 'BONJOUR', 'Le mot doit être en majuscules'"},
            {"name": "a", "assertion": "assert crie_message('a') == 'A', 'Le mot doit être en majuscules'"},
            {"name": "ile", "assertion": "assert crie_message('ile') == 'ILE', 'Le mot doit être en majuscules'"},
            {"name": "Code", "assertion": "assert crie_message('Code') == 'CODE', 'Le mot doit être en majuscules'"},
        ],
        "success_message": "La tour répond par un écho puissant.",
        "failure_hint": "La méthode `.upper()` transforme une chaîne en majuscules.",
    },
    {
        "id": "level-9-step-2",
        "level": 9,
        "step": 18,
        "title": "Le message inversé",
        "zone": "La Tour des Chaines",
        "story": "Un vieux parchemin est écrit à l'envers. Tu dois remettre les lettres dans l'ordre inverse pour percer son secret.",
        "instructions": "Ecris une fonction qui reçoit un mot et renvoie ce mot à l'envers.",
        "short_objective": "Inverser une chaîne.",
        "function_name": "inverse_message",
        "starter_code": "def inverse_message(message):\n    # Retourne le message à l'envers\n    return ''\n",
        "examples": make_examples(("inverse_message('abc')", "'cba'"), ("inverse_message('kayak')", "'kayak'")),
        "tests": [
            {"name": "abc", "assertion": "assert inverse_message('abc') == 'cba', 'abc inversé donne cba'"},
            {"name": "kayak", "assertion": "assert inverse_message('kayak') == 'kayak', 'kayak reste kayak'"},
            {"name": "python", "assertion": "assert inverse_message('python') == 'nohtyp', 'python inversé donne nohtyp'"},
            {"name": "a", "assertion": "assert inverse_message('a') == 'a', 'Une lettre seule reste la même'"},
            {"name": "ile", "assertion": "assert inverse_message('ile') == 'eli', 'ile inversé donne eli'"},
        ],
        "success_message": "Le parchemin révèle une carte secrète.",
        "failure_hint": "Tu peux utiliser le découpage `[::-1]` pour inverser une chaîne.",
    },
    {
        "id": "level-10-step-1",
        "level": 10,
        "step": 19,
        "title": "Les pierres du volcan",
        "zone": "Le Volcan des Algorithmes",
        "story": "Avant le sommet, tu dois examiner une liste de pierres et garder seulement celles qui brillent vraiment.",
        "instructions": "Ecris une fonction qui reçoit une liste de nombres et renvoie combien de nombres sont plus grands que 5.",
        "short_objective": "Combiner liste, boucle et condition.",
        "function_name": "compte_grandes_pierres",
        "starter_code": "def compte_grandes_pierres(nombres):\n    compteur = 0\n    # Compte les nombres strictement plus grands que 5\n    return compteur\n",
        "examples": make_examples(("compte_grandes_pierres([1, 6, 7])", "2"), ("compte_grandes_pierres([5, 5, 5])", "0")),
        "tests": [
            {"name": "1 6 7", "assertion": "assert compte_grandes_pierres([1, 6, 7]) == 2, '6 et 7 sont plus grands que 5'"},
            {"name": "5 5 5", "assertion": "assert compte_grandes_pierres([5, 5, 5]) == 0, '5 n\\'est pas plus grand que 5'"},
            {"name": "10 2 8 1", "assertion": "assert compte_grandes_pierres([10, 2, 8, 1]) == 2, '10 et 8 sont plus grands que 5'"},
            {"name": "vide", "assertion": "assert compte_grandes_pierres([]) == 0, 'Une liste vide donne 0'"},
            {"name": "6 6 6", "assertion": "assert compte_grandes_pierres([6, 6, 6]) == 3, 'Les trois nombres sont plus grands que 5'"},
        ],
        "success_message": "Le volcan gronde doucement pour t'encourager.",
        "failure_hint": "Parcours la liste et ajoute 1 au compteur quand un nombre est plus grand que 5.",
    },
    {
        "id": "level-10-step-2",
        "level": 10,
        "step": 20,
        "title": "Le code du cratère",
        "zone": "Le Volcan des Algorithmes",
        "story": "Au sommet, le cratère demande un mot de passe spécial : il faut compter les voyelles d'un mot pour apaiser la lave.",
        "instructions": "Ecris une fonction qui reçoit un mot et renvoie le nombre de voyelles a, e, i, o, u qu'il contient.",
        "short_objective": "Combiner boucle, condition et chaîne.",
        "function_name": "compte_voyelles",
        "starter_code": "def compte_voyelles(mot):\n    compteur = 0\n    # Compte les voyelles a, e, i, o, u\n    return compteur\n",
        "examples": make_examples(("compte_voyelles('python')", "1"), ("compte_voyelles('ile')", "2")),
        "tests": [
            {"name": "python", "assertion": "assert compte_voyelles('python') == 1, 'python contient 1 voyelle'"},
            {"name": "ile", "assertion": "assert compte_voyelles('ile') == 2, 'ile contient 2 voyelles'"},
            {"name": "banane", "assertion": "assert compte_voyelles('banane') == 3, 'banane contient 3 voyelles'"},
            {"name": "sky", "assertion": "assert compte_voyelles('sky') == 0, 'sky ne contient pas de voyelle parmi a e i o u'"},
            {"name": "oasis", "assertion": "assert compte_voyelles('oasis') == 3, 'oasis contient 3 voyelles'"},
        ],
        "success_message": "Tu apaises le volcan et deviens un Pythonaute légendaire.",
        "failure_hint": "Parcours les lettres du mot et ajoute 1 quand la lettre est dans 'aeiou'.",
    },
]


EXERCISES_BY_ID = {exercise["id"]: exercise for exercise in EXERCISES}


def get_exercise_or_none(exercise_id: str) -> ExerciseDict | None:
    return EXERCISES_BY_ID.get(exercise_id)


def serialize_exercise_summary(exercise: ExerciseDict) -> Dict[str, Any]:
    return {
        "id": exercise["id"],
        "level": exercise["level"],
        "step": exercise["step"],
        "title": exercise["title"],
        "zone": exercise["zone"],
        "short_objective": exercise["short_objective"],
    }


def serialize_exercise_detail(exercise: ExerciseDict) -> Dict[str, Any]:
    return {
        **serialize_exercise_summary(exercise),
        "story": exercise["story"],
        "instructions": exercise["instructions"],
        "function_name": exercise["function_name"],
        "starter_code": exercise["starter_code"],
        "examples": exercise["examples"],
        "success_message": exercise["success_message"],
        "failure_hint": exercise["failure_hint"],
    }
